sources:
  - name: raw_ecommerce
    description: Raw GA4 BigQuery export data
    database: zmcp-final
    schema: raw_ecommerce
    tables:
      - name: events
        description: GA4 event-level data
        columns:
          - name: event_date
            description: Date of the event (YYYYMMDD format)
          - name: event_timestamp
            description: Event timestamp in microseconds (UTC)
          - name: event_name
            description: Name of the event (e.g. page_view, purchase, session_start)
          - name: event_params
            description: Repeated record of event parameter key-value pairs
          - name: event_previous_timestamp
            description: Timestamp of the previous event in microseconds (UTC)
          - name: event_value_in_usd
            description: Event value in USD
          - name: event_bundle_sequence_id
            description: Sequential ID of the event bundle
          - name: event_server_timestamp_offset
            description: Timestamp offset between server and client in microseconds
          - name: user_id
            description: User ID set via setUserId API
          - name: user_pseudo_id
            description: Pseudonymous ID generated by GA4 (client ID)
          - name: privacy_info
            description: Privacy-related settings for the user
          - name: user_properties
            description: Repeated record of user property key-value pairs
          - name: user_first_touch_timestamp
            description: Timestamp of the user's first app open or site visit in microseconds
          - name: user_ltv
            description: Lifetime value record for the user
          - name: device
            description: Device information (category, brand, model, OS, browser, etc.)
          - name: geo
            description: Geographic information (continent, country, region, city)
          - name: app_info
            description: App information (id, version, install source)
          - name: traffic_source
            description: Traffic source that first acquired the user (medium, source, campaign)
          - name: stream_id
            description: Numeric ID of the data stream
          - name: platform
            description: Platform (WEB, IOS, ANDROID)
          - name: event_dimensions
            description: Event dimension record
          - name: ecommerce
            description: Ecommerce data (total value, purchase revenue, shipping, tax, etc.)
          - name: items
            description: Repeated record of item-level data (item_id, item_name, price, quantity, etc.)
  - name: raw_backend
    description: Raw data from the backend database
    database: zmcp-final
    schema: raw_backend
    config:
      freshness: { count: 24, period: hour }

    tables:
      - name: users
        description: Website users
        config:
          loaded_at_field: created_at
        columns:
          - name: user_pseudo_id
            description: ID created by GA4's stream
          - name: user_id
            description: Sequential identifying number
          - name: email
            description: Users' email address
          - name: name
            description: Users' name and surname
          - name: created_at
            description: Timestamp when the user was created

      - name: orders
        description: Website orders
        config:
          loaded_at_field: created_at
        columns:
          - name: transaction_id
            description: Transaction ID sent to GA4
          - name: purchase_revenue
            description: Purchase revenue
          - name: shipping_value
            description: Shipping value
          - name: total_item_quantity
            description: Total item quantity
          - name: user_id
            description: Sequential identifying number
          - name: order_id
            description: Order ID from our backend
          - name: status
            description: Order status
          - name: created_at
            description: Timestamp

      - name: order_items
        description: Items related to an order
        columns:
          - name: transaction_id
            description: Transaction ID sent to GA4
          - name: item_id
            description: Item ID
          - name: item_name
            description: Item name
          - name: item_category
            description: Item category
          - name: price
            description: Item price
          - name: quantity
            description: Quantity
